version: "3.4"
services:
  golang:
    container_name: golang
    image: aimvector/golang:1.0.0
    build: 
      context: ../../
      dockerfile: docker/Dockerfile
      target: prod
    volumes:
    - ../../:/app/
    ports:
      - 5001:5000
      - 2345:2345
    security_opt:
      - "seccomp:unconfined"